### ISSUE TITLE
Organize problems on trees-graphs.md 

### ISSUE THREAD

**Issue by elaguerta** [WomenWhoCode/wwcsf-algos#33]
Please edit the Problem Sets section on this markdown file: https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/trees-graphs.md
- Make 2 different sections for Tree problems and Graph problems. 
- Organize problems by difficulty into tables. Here is an example from Linked Lists: https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/linked-lists.md#problem-sets

Add tables for Tree problems:
- [Easy Tree Problems](https://leetcode.com/explore/featured/card/top-interview-questions-easy/94/trees/): pick at least 3 Easy ones (some of these are not labeled easy)
- [Medium Tree Problems](https://leetcode.com/explore/interview/card/top-interview-questions-medium/108/trees-and-graphs/): Binary Tree Inorder Traversal, Populating Next Right Pointers in Each Node, Construct Binary Tree from Preorder and Inorder Traversal
- [Hard Tree Problems](https://leetcode.com/explore/interview/card/top-interview-questions-hard/118/trees-and-graphs/), Word Ladder, Lowest Common Ancestor of a Binary Tree, Binary Tree Maximum Path Sum
- Please provide a link to the official Leetcode problem page, instead of to the card or article. For example, [don't link to this page](https://leetcode.com/explore/interview/card/top-interview-questions-easy/94/trees/555/), [link to this one](https://leetcode.com/problems/maximum-depth-of-binary-tree/). You will have to search leetcode for the problem title to find the correct page with a URL that starts with `leetcode.com/problems`. 
- Only post problems that are available through a free leetcode account.

**Comment by the-unxplainable** [comment]
Hi @elaguerta! For the Easy Tree Problems link - only 2 of the problems have unlocked solutions and 1 of those 2 problems is labeled medium. Should I add only 2 problems and put them both under the Easy Problems Table?
