### ISSUE TITLE
trees-graphs.md: Add links to Jeff Erickson's algorithm text

### ISSUE THREAD

**Issue by elaguerta** [WomenWhoCode/wwcsf-algos#37]
Update our trees-graphs topic page: https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/trees-graphs.md

With links to specific trees and graphs chapters in this online text:
http://jeffe.cs.illinois.edu/teaching/algorithms/

**Comment by arch92** [comment]
I will be taking this issue.
