### ISSUE TITLE
Update problem sets arrays-strings.md

### ISSUE THREAD

**Issue by elaguerta** [WomenWhoCode/wwcsf-algos#51]
Edit our topic page on arrays-strings, which lives here: https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/arrays-strings.md

- [ ] Select 3 Easy, 3 Medium, and 3 Hard problems 

- [ ] Put them in a table format, see https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/linked-lists.md for an example

- [ ] Please include these two problems in the Medium section:
- https://leetcode.com/problems/merge-intervals/
- https://leetcode.com/problems/interval-list-intersections/

**Comment by ielin** [comment]
What problems should be added in the Easy and Hard section?
