### ISSUE TITLE
Add a stacks and queues page and provide content. 

### ISSUE THREAD

**Issue by elaguerta** [WomenWhoCode/wwcsf-algos#66]
Add a stacks and queues topic page to ./topics/stacks_queues.md

Resources for this issue:
- The template for a topic page: https://github.com/WomenWhoCode/wwcsf-algos/blob/master/topics/template.md
- Problem sets to select problems for the topic page: https://github.com/WomenWhoCode/wwcsf-algos#2e-problem-sets
- Leetcode curated Top Interview Questions:
  - Easy: https://leetcode.com/explore/interview/card/top-interview-questions-easy/ 
  - Medium: https://leetcode.com/explore/interview/card/top-interview-questions-medium/ 
  - Hard: https://leetcode.com/explore/interview/card/top-interview-questions-hard/
  
Please make sure you have done the following before requesting a review:
- [ ] In the problem set tables, make sure that the code examples link points to the correct folder in https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/
- [ ] Please make sure that all leetcode problems you select are accessible without a leetcode account. If the solution is not accessible, you can still use the problem, just link the solution to the solution discussion.
- [ ] Please add a link to your new topic page to the repo's README in this section: https://github.com/WomenWhoCode/wwcsf-algos#3-resources-and-problem-sets-by-category

**Comment by spriyam** [comment]
@elaguerta Please assign this issue to me.Thanks!
